"""EnergyPlus EPW export from either DWD/HOSTRADA or CERRA."""
from __future__ import annotations
import numpy as np
from hostrada4py import hostrada as hs
from ._weather_common import weather_dataframe,ensure_target,local_time,unique

def _unique_preserve_order(values): return unique(values)
def _required_vars(apply_weather_correction=False):
    required=["tas","tdew","hurs","ps","sfcWind","sfcWind_direction","rsds","clt"]
    if apply_weather_correction: required.append("uhi")
    available=hs.provider_capabilities().variables
    provider_required=[variable for variable in required if variable in available]
    return _unique_preserve_order(provider_required)

def create_energyplus_weather_file(lon,lat,start,end,output_file="HOSTRADA_EnergyPlus.epw",*,
        location_name="HOSTRADA",country="DEU",source=None,station_id="999999",tz="Europe/Berlin",
        altitude=0.0,apply_weather_correction=False,cache_dir="hostrada_cache",cache_strategy=None,
        subset_margin_cells=None,provider=None,verbose=True,**kwargs):
    df=weather_dataframe(lon,lat,start,end,_required_vars(apply_weather_correction),tz=tz,altitude=altitude,
        apply_weather_correction=apply_weather_correction,cache_dir=cache_dir,cache_strategy=cache_strategy,
        subset_margin_cells=subset_margin_cells,provider=provider,verbose=verbose)
    path=ensure_target(output_file,"HOSTRADA_EnergyPlus.epw"); times=local_time(df,tz)
    src=source or hs.get_provider(provider).name.upper()
    utc_offset=times[0].utcoffset().total_seconds()/3600 if len(times) else 0
    headers=[f"LOCATION,{location_name},-,{country},{src},{station_id},{lat:.4f},{lon:.4f},{utc_offset:.1f},{altitude:.1f}",
             "DESIGN CONDITIONS,0","TYPICAL/EXTREME PERIODS,0","GROUND TEMPERATURES,0","HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
             "COMMENTS 1,Generated by hostrada4py provider overlay","COMMENTS 2,Times converted from UTC to local timezone","DATA PERIODS,1,1,Data,Sunday,1/1,12/31"]
    with path.open("w",encoding="utf-8",newline="") as f:
        f.write("\n".join(headers)+"\n")
        for i,(t,row) in enumerate(zip(times,df.to_dict("records"))):
            pressure=(row.get("ps") if np.isfinite(row.get("ps",np.nan)) else row.get("psl",1013.25))*100
            cloud=row.get("clt",0); cloud=cloud/10 if np.isfinite(cloud) and cloud>10 else cloud
            fields=[t.year,t.month,t.day,t.hour+1,60,"?9?9?9?9E0?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9?9",
                    row.get("tas",99.9),row.get("tdew",99.9),row.get("hurs",999),pressure,9999,9999,9999,
                    row.get("rsds",9999),row.get("dni",9999),row.get("dhi",9999),999999,999999,999999,9999,
                    row.get("sfcWind_direction",999),row.get("sfcWind",999),cloud,cloud,9999,99999,9,999999999,999,0.999,999,99,0.999,999,99]
            f.write(",".join(str(x) for x in fields)+"\n")
    return path
create_weather_file=create_energyplus_weather_file
